language: node_js  # 设置语言

node_js:
  - 10 # 指定node.js版本

cache: npm # 开启缓存

services:
  - mongodb

install:
  - yarn

script:
  - npm run build-cal

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/calendar
  on:
    branch: master