export const _FETCH_EVTS = '_FETCH_EVTS';

export const _FETCH_EVTS_SUCCESS = '_FETCH_EVTS_SUCCESS';

export const _FETCH_EVTS_ERROR = '_FETCH_EVTS_ERROR';

export const _FETCH_MONTH_EVTS = '_FETCH_MONTH_EVTS';

export const _FETCH_MONTH_EVTS_SUCCESS = '_FETCH_MONTH_EVTS_SUCCESS';

export const _FETCH_EVTS_OF_DATES = '_FETCH_EVTS_OF_DATES';

export const _FETCH_EVTS_OF_DATES_SUCCESS = '_FETCH_EVTS_OF_DATES_SUCCESS';

export const _SAVE_EVT_ = '_SAVE_EVT_';

export const _SAVE_EVT_SUCCESS = '_SAVE_EVT_SUCCESS';

export const _RESET_SAVE_STATUS = '_RESET_SAVE_STATUS';
