export const _FETCH_EVTS = '_FETCH_EVTS';

export const _FETCH_EVTS_SUCCESS = '_FETCH_EVTS_SUCCESS';

export const _FETCH_EVTS_ERROR = '_FETCH_EVTS_ERROR';

export const _FETCH_MONTH_EVTS = '_FETCH_MONTH_EVTS';

export const _FETCH_MONTH_EVTS_SUCCESS = '_FETCH_MONTH_EVTS_SUCCESS';